obstacle_range: 2.5
raytrace_range: 3.0
#footprint: [[-0.31, -0.69], [-0.31, 0.25], [0.31, 0.25], [0.31, -0.69]]
footprint:  [[-0.1225, -0.26], [-0.1225, 0.26], [0.1225, 0.26], [0.1225, -0.26]]
#robot_radius: ir_of_robot
inflation_radius: 0.4 #0.55#0.22

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: laser_frame, data_type: LaserScan, topic: scan, marking: true, clearing: true}

# footprint:  [[-0.1225, -0.26], [-0.1225, 0.26], [0.1225, 0.26], [0.1225, -0.26]]
# transform_tolerance: 0.5
# map_type: costmap
# obstacle_layer:
#  enabled: true
#  obstacle_range: 3.0
#  raytrace_range: 3.5
#  inflation_radius: 0.2
#  track_unknown_space: false
#  combination_method: 1
#  observation_sources: laser_scan_sensor
#  laser_scan_sensor: {sensor_frame: scanmatcher_frame, data_type: LaserScan, topic: /scan, marking: true, clearing: false}
# inflation_layer:
#   enabled:              true
#   cost_scaling_factor:  1.0  
#   inflation_radius:     0.2
# obstacle_layer:
#      enabled: true
#      obstacle_range: 5.0
#      raytrace_range: 1.0
#      observation_sources: "scan"
#      observation_persistence: 0.0
#      inf_is_valid: false
#      scan:
#        data_type: LaserScan
#        topic: scan  