local_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 10.0
  publish_frequency: 10.0 #2
  static_map: false
  rolling_window: true
  width: 6.0 #5#2
  height: 6.0 #5#2
  resolution: 0.05

